# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unfuck < Formula
  desc "Config linter for humans — YAML, Dockerfiles, K8s, GitHub Actions, and more"
  homepage "https://unfuck.dev"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/elementcreations/unfuck-release/releases/download/v0.9.0/unfuck_0.9.0_darwin_amd64.tar.gz"
      sha256 "b93b242562525ea6a8a78998f3288158394d63d5029905e6e4e37b9039565984"

      def install
        bin.install "unfuck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/elementcreations/unfuck-release/releases/download/v0.9.0/unfuck_0.9.0_darwin_arm64.tar.gz"
      sha256 "f2e1457a341d6641cf515fb0a0fa6bcbadfa52ae9f36ae8878bfa14c73118796"

      def install
        bin.install "unfuck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/elementcreations/unfuck-release/releases/download/v0.9.0/unfuck_0.9.0_linux_amd64.tar.gz"
      sha256 "a82adbaed801b2b12795840b2944aeae17f3af4c58d284cd5bac90bff03e73ee"
      def install
        bin.install "unfuck"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elementcreations/unfuck-release/releases/download/v0.9.0/unfuck_0.9.0_linux_arm64.tar.gz"
      sha256 "abffd8793fe03ced993eca1b762d29934542c8af4284d3c03b7f8c3d4267c8dc"
      def install
        bin.install "unfuck"
      end
    end
  end

  test do
    system "#{bin}/unfuck", "--version"
  end
end
