# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unfuck < Formula
  desc "Config linter for humans — YAML, Dockerfiles, K8s, GitHub Actions, and more"
  homepage "https://unfuck.dev"
  version "0.17.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/elementcreations/unfuck-release/releases/download/v0.17.0/unfuck_0.17.0_darwin_amd64.tar.gz"
      sha256 "81b6deb146d4acffbb3a195949f4ffb93d972bcd83fb360a975c012578488e0e"

      define_method(:install) do
        bin.install "unfuck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/elementcreations/unfuck-release/releases/download/v0.17.0/unfuck_0.17.0_darwin_arm64.tar.gz"
      sha256 "3f43b0608025930a5e29bdea4bca24e8b62492f983700834be106682c2c5922f"

      define_method(:install) do
        bin.install "unfuck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/elementcreations/unfuck-release/releases/download/v0.17.0/unfuck_0.17.0_linux_amd64.tar.gz"
      sha256 "5bc895b5bc8a8dc99eff0d96201ad6191f0e4f8571b8430dd87b062ff8ffc8e9"
      define_method(:install) do
        bin.install "unfuck"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elementcreations/unfuck-release/releases/download/v0.17.0/unfuck_0.17.0_linux_arm64.tar.gz"
      sha256 "d0a15c6e821d7c9182b6c1f96415fb0bd39050087345800679bcac0d347b9b86"
      define_method(:install) do
        bin.install "unfuck"
      end
    end
  end

  test do
    system "#{bin}/unfuck", "--version"
  end
end
