# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UnfuckRelease < Formula
  desc "Config linter for humans — YAML, Dockerfiles, K8s, GitHub Actions, and more"
  homepage "https://unfuck.dev"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/elementcreations/unfuck-release/releases/download/v0.2.3/unfuck_0.2.3_darwin_amd64.tar.gz"
      sha256 "3bc49c6d4cdc85a55295a65b189e0510deffa6cbe735e96ce8cd45cf0de11da3"

      def install
        bin.install "unfuck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/elementcreations/unfuck-release/releases/download/v0.2.3/unfuck_0.2.3_darwin_arm64.tar.gz"
      sha256 "6a9c3d1c3419bc13f65e263ad7db21e67e3f4f1c302dec2f984acc6353f9e01f"

      def install
        bin.install "unfuck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/elementcreations/unfuck-release/releases/download/v0.2.3/unfuck_0.2.3_linux_amd64.tar.gz"
      sha256 "aa36dd45b14c0ade7a5a05426c8624cda98bd52acbadb480ce7cf9415601a334"
      def install
        bin.install "unfuck"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elementcreations/unfuck-release/releases/download/v0.2.3/unfuck_0.2.3_linux_arm64.tar.gz"
      sha256 "50feff7971c8f41b0aa144056b9caa27fc24fe91ecb1583ab8f9d44f8e615d10"
      def install
        bin.install "unfuck"
      end
    end
  end

  test do
    system "#{bin}/unfuck", "--version"
  end
end
